// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbC_cPIoSoUshyVKuDGKrbdeKbj3AdpCY',
    appId: '1:899538874167:android:e193d07cf812d548b874b2',
    messagingSenderId: '899538874167',
    projectId: 'receitas-da-vovozinha-89a13',
    databaseURL: 'https://receitas-da-vovozinha-89a13-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'receitas-da-vovozinha-89a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sch6VYyDi-p3gcjFQRa63NrgtVrmUjE',
    appId: '1:899538874167:ios:ca0b1314ed361af1b874b2',
    messagingSenderId: '899538874167',
    projectId: 'receitas-da-vovozinha-89a13',
    databaseURL: 'https://receitas-da-vovozinha-89a13-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'receitas-da-vovozinha-89a13.appspot.com',
    androidClientId: '899538874167-incpco006r5j407dkage6eabgdor9l8m.apps.googleusercontent.com',
    iosClientId: '899538874167-n4qpt6i173sh7a3babv7bdjjp2v4hbdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.receitasdavovozinha',
  );
}
